
/****************************************************************************
 *
 * Function:	email_files_send, email_file_send, email_send
 *
 * Description:	Routines to send email to specified user.
 *
 * Author:	Renee Carter
 *
 ***************************************************************************/

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/uio.h>
#include <strings.h>
#include <string.h>
#include "client_dir.h"
#include "client_files.h"
#include "client_lib.h"
#include "client_prototypes.h"
#include "global_params.h"
#include "dir.h"
#include "global_defines.h"
#include "strcpy.h"
#include "trans_prototypes.h"

#include "global_debug.h"


void email_send(char *replyto, char *recipients, char *subject, char *body)
{
    DBG();
    char command[512];
    char host_name[64];
    FILE *po;

    if (replyto[0] != 0)
    {
        sprintf (command, "/usr/lib/sendmail  -f%s %s", replyto, recipients);
    }
    else
    {
        sprintf (command, "/usr/lib/sendmail  %s", recipients);
    }
    po = popen (command,"w");
    fprintf (po, "To: %s\n", recipients);
    if (replyto[0] != '\0')
    {
        fprintf(po, "From:  %s\n", replyto);
        fprintf(po, "Reply-To:  %s\n", replyto);
    }
    /* Write out the email subject */
    if (subject[0] != '\0')
        fprintf (po, "Subject: %s\n\n", subject);
    /* Write out the email body */
    fprintf(po, "%s\n\n", body);
    /* Get the name of the current machine */
    gethostname(host_name, 64);
    fprintf(po, "-- Message generated by %s on %s\n", so.program, host_name);
    pclose (po);
    return;
}
