#ifndef mask_server_paths_h
#define mask_server_paths_h
/* Defines for mask and template paths */
#define CONTRACT_DIR "contract_tables"
#define MASKSET_TABLE "contract_tables/maskset.table"
#define MASKSET_ROOT "maskset.table"
#define MASKSET_LOG "contract_tables/mask_log"
#define PC_TABLE "contract_tables/pc.table"
#define PC_ROOT "pc.table"
#define PC_LOG "contract_tables/pc_log"
#define H_TABLE "contract_tables/h.table"
#define H_ROOT "h.table"
#define H_LOG "contract_tables/h_log"
#define DB_DATA_DIR "db_admin"
#define TMP_DB_DATA_DIR "db_admin/tmp_files"
#define TMP_DB_DATA_PATH "db_admin/tmp_files/"
#define DB_DATA_PATH "db_admin/"
#define DISK_FILE "db_admin/disk_usage"
#define COM1SERIAL_FILE "serial_tables/com1tbl"
#define COM1SERIAL_LEAF "com1serial_file"
#define COM1SERIAL_LOG "db_admin/com1serial_log"
#define TMPL_OWNERS "tmpl_owners"
#define MASKPREPSTATE ".MaskPrepState"
#define RESEND_PATH "resend_data/"
#define RESEND_FILE "rmt_log/resend_file"
#define TMP_RESEND_FILE "log/tmp_resend_file"
#define CNB_FILE "db_admin/maskshop.cnb"
#define GLOBAL_DATA "global_data/global"
#define GLOBAL_DRIVER_TABLE "db_admin/driver.files"
#define SYSADMIN_AUTH "db_admin/sysadmin.auth"
#define TOKYO_AUTH "db_admin/tokyo.auth"
#define DB_ADMIN_FILE "db_admin/db_admin_file"
#define SYSADMIN_INFO "db_admin/sysadmin.info"
#define APPROVE_AUTH "db_admin/approve.auth"
#define APPROVE_INFO "db_admin/approve.info"
#define GLOBAL_MASK_FILE "db_admin/mask.sets"
#define TMP_MASK_FILE "mask.sets"
#define BACKUP_MASK_FILE ".backup.sets"
#define WLFL_PATH "wafer_design/"
#define CONTROL_GROUP_DIR "control_groups"
#define WLFL_DIR "wafer_design"
#define WLFL_DIR "wafer_design"
#define GLBL_WL_FILE "wafer_design/wafer.lines"
#define WAFER_LIES "wafer.lines"
#define GLBL_DSGN_FILE "wafer_design/design.groups"
/* File with names of all closure, orient, option and driver files to send */

/* Defines for global design and wafer line paths  */
#define DESIGN_GROUPS "wafer_design/design.groups"
#define DSGN_DIR "wafer_design"
#define DSGN_DATA_DIR "design_data"
#define DSGN_DLTA_DIR "design_dlta"
#define DSGNO_DLTA_DIR "off_design_dlta"
#define DSGN_PATH "design_data/"
#define DSGN_DLTA "design_dlta/"
#define DSGNO_DIR "off_design_data"
#define DSGNO_PATH "off_design_data/"
#define DSGNO_DLTA "off_design_dlta/"

#define PC_PATH "pc_data/"
#define PC_DIR "pc_data"
#define PC_DLTA_DIR "pc_dlta"
#define TMP_PC_PATH "pc_dlta/tmp_files/"
#define PC_DLTA "pc_dlta/"
#define PC_LEN 8
#define PC_BACKUP "pc_backup/"

#define TMPL_DIR "wafer_data"
#define TMPL_PATH "wafer_data/"
#define TMP_TMPL_PATH "tmpl_tmp/"
#define TMPL_DLTA_DIR "wafer_dlta"
#define TMPL_DLTA "wafer_dlta/"
#define TMPLO_DIR "off_wafer_data"
#define TMPLO_PATH "off_wafer_data/"
#define TMPLO_DLTA_DIR "off_wafer_dlta"
#define TMPLO_DLTA "off_wafer_dlta/"
#define MASK_DIR "mask_data"
#define MASK_PATH "mask_data/"
#define TMP_MASK_PATH "mask_tmp/"
#define MASK_DLTA "mask_dlta/"
#define MASK_DLTA_DIR "mask_dlta"

/* Defines for PC library names */
#define PC_USR ".pc_usr"
#define PC_STATE ".pc_state"
#define GLBL_PATH_LEN strlen(GLBL_PATH)
#define DSGN_PATH_LEN strlen(DSGN_PATH)
#define TMPL_PATH_LEN strlen(TMPL_PATH)
#define MASK_PATH_LEN 20
#define TMPL_DLTA_LEN strlen(TMPL_DLTA);
#define MASK_DLTA_LEN strlen(MASK_DLTA);
#define CRT_SUFFIX ".crt"
#define STATE ".state"
/* File holding authorized system administrators */
#define SYSADMIN_AUTH "db_admin/sysadmin.auth"
#define APPROVE_AUTH "db_admin/approve.auth"
#define REMOTE_SERVER_TABLE "db_admin/remote_servers"
#define RMT_SERVER_TABLE "db_admin/rmt_servers"
#define GLOBAL_PARAMS "db_admin/global_params"
#define DRIVER_PATH "global_data/"
#define DRIVER_DIR "global_data"
#define WAFER_LINES "wafer_design/wafer.lines"
#define PC_FILE "db_admin/pc_libs"

/* Defines for serial num tables */
#define MOS6SERIAL_FILE "mos6tbl"
#define MOS6LOG_FILE "serial_tables/mos6log"
#define MOS16SERIAL_FILE "mos16tbl"
#define MOS16LOG_FILE "serial_tables/mos16log"
#define MOS17SERIAL_FILE "mos17tbl"
#define MOS17LOG_FILE "serial_tables/mos17log"
#define MOS21SERIAL_FILE "mos21tbl"
#define MOS21LOG_FILE "serial_tables/mos21log"
#define CONTRACT_FILE "db_admin/contract_num"
#define PCNUM_FILE "db_admin/pc_num"
#define SITE_REG_FILE "registry/site_reg."
#endif /* ifdef for mask_server_paths_h */
