add_email_entry.c
add_file_entry.c
add_file_line.c
add_line.c
add_site_entry.c
alarm.c
big_disk_usage.c
block_get.c
block_put.c
check_disk_space.c
check_owner.c
check_reg.c
close_down.c
company.c
compare_names.c
compare_sites.c
core_id_crypt.c
create_secure_keyword.c
cron_dlt_files.c
customer_set.c
dbsend_file.c
dbsend_files.c
dir.c
disk_usage.c
disk_usage_check.c
dlt_big_file.c
dlt_empty_global_files.c
dlt_file_entry.c
dlt_file_line.c
dlt_history_files.c
dlt_keyword_entries.c
dlt_old_sites.c
dlt_site_entry.c
dlt_time_calc.c
dlt_time_calc.c
edc_reg.c
email.c
email_send.c
entry.c
entry.c
extend_big_file.c
external_transweb.c
file.c
file_append.c
file_copy.c
file_rcv.c
file_rename.c
file_type_get.c
files.c
files.c
files_copy.c
files_dlt.c
files_dlt_transient.c
files_get.c
files_list.c
files_put.c
files_rcv.c
find_email.c
find_email.c
find_reg_request.c
fss.c
gcc -O   -c -o adler32.o adler32.c
gcc -O   -c -o compress.o compress.c
gcc -O   -c -o crc32.o crc32.c
gcc -O   -c -o deflate.o deflate.c
gcc -O   -c -o gzio.o gzio.c
gcc -O   -c -o infback.o infback.c
gcc -O   -c -o inffast.o inffast.c
gcc -O   -c -o inflate.o inflate.c
gcc -O   -c -o inftrees.o inftrees.c
gcc -O   -c -o trees.o trees.c
gcc -O   -c -o uncompr.o uncompr.c
gcc -O   -c -o zutil.o zutil.c
get_big_file.c
get_parallel_data.c
get_random.c
get_random_index.c
get_release.c
get_release_file.c
get_site.c
global_debug.c
global_sql_lib.c
history_big_file.c
info_big_file.c
init_rmt_socket.c
init_socket.c
init_ssl_socket.c
init_trans_socket.c
ip_addr.c
keyword.c
keyword.c
keyword_read.c
keyword_send.c
ldapfsl.c
ldapfsl_trans.c
line_get.c
list.c
lock_file.c
log.c
log.c
lookup_keyword.c
lookup_release_keyword.c
mask_filelist_check.c
mask_msg_server_send.c
mod_big_file.c
mod_lock_cnt.c
names_build.c
open_big_file.c
owner_dlt.c
owner_dlt.c
password_crypt.c
password_encrypt.c
process_request.c
put_big_file.c
put_msg.c
put_parallel_data.c
put_success_msg.c
query_user.c
rcv_file.c
read_global_params.c
reg.c
reg_lookup.c
reg_query.c
remote_email_send.c
report_gen.c
report_gen.c
report_log.c
request.c
resend_reg.c
rmt_lib.c
rmt_server.c
rmv_dups.c
rtv_user_email.c
search_email_file.c
search_registry.c
send_file.c
send_files.c
send_rtv_email.c
send_secure_keyword.c
send_secure_keyword.c
server.c
server_lib.c
set_trans_disk_usage.c
shared_memory.c
shut_down.c
size_check_big_file.c
sort.c
sql_destinations_mapping.c
sql_keyword_mapping.c
sql_lib.c
sql_reg.c
ssl_common.c
ssl_init.c
ssl_rmt_lib.c
ssl_rmt_lib.c
ssl_server.c
ssl_server_lib.c
ssl_utils.c
status_big_file.c
strcmp1err.c
strcpy.c
strdlt_quotes.c
strip_email_trailors.c
support.c
time_calc.c
time_stamp.c
time_stamp.c
trans1step_download.c
trans1step_upload.c
trans_server_globals.c
trans_sql_lib.c
transdirlist.c
transweb.c
transweb_keyword.c
transweb_reg.c
user_autoreg.c
x500.c
