#ifndef WINDOWS_NT4
/****************************************************************************
 *
 * Function:	email_files_send, email_file_send, email_send
 *
 * Description:	Routines to send email to specified user.
 *
 * Author:	Renee Carter
 *
 ***************************************************************************/

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/uio.h>
#include <strings.h>
#include <string.h>
#include "client_dir.h"
#include "client_files.h"
#include "client_lib.h"
#include "client_prototypes.h"
#include "global_params.h"
#include "dir.h"
#include "global_defines.h"
#include "strcpy.h"
#include "trans_prototypes.h"
#include "global_debug.h"
#include "email_handling.h"


void email_files_send(
    char *replyto,
    char *recipients,
    char *subject,
    char *file1,
    char *file2)
{
    int fd = 0;
    int size  = 0;
    char buffer[10 * BLOCK_SIZE];

    DBG("libraries/db_libs/shared_client_lib/source/email_send.c");

    /* Open file with message to send */
    if ((fd = open(file1, O_RDONLY)) == EOF  || (size = read(fd, buffer, sizeof(buffer) -1)) <= 0)
    {
        sprintf(buffer, "Unable to read output from file '%s'\n", file1);
        size = 0;
    }
    /* Close the output script */
    close(fd);

    /* Open file with message to send */
    if ((fd = open(file2, O_RDONLY)) == EOF)
    {
        sprintf(&buffer[size], "\nUnable to read output from file '%s'\n", file2);
    }
    else
    {
       int read_size = read(fd, &buffer[size], sizeof(buffer) -1 -size);
       if (read_size > 0)
       {
            size += read_size;
       }
    }
    /* Close the output script */
    close(fd);

    if (size > 0)
    {
        buffer[size] = 0;
        email_send(replyto, recipients, subject, buffer);
    }

} /* End email_files_send */



void email_file_send(
    char *replyto,
    char *recipients,
    char *subject,
    char *file)
{
    int fd;
    int size;
    char buffer[5 * BUFFER_SIZE];

    /* Open file with message to send */
    if ((fd = open(file, O_RDONLY)) == EOF)
    {
        sprintf(buffer, "Unable to read output from file '%s'\n", file);
    }
    else
    {
        if ((size = read(fd, buffer, sizeof(buffer) -1)) > 0)
        {
            buffer [size] = 0;
            email_send(replyto, recipients, subject, buffer);
        }
        close(fd);
    }

} /* End email_file_send */



short email_msg_file_send(
        char *replyto,
        char *recipients,
        char *subject,
        char *msg,
        char *file)
{
    int fd;
    int size;
    char buffer[5 * BUFFER_SIZE];

    /* Open file with message to send */
    if ((fd = open(file, O_RDONLY)) == EOF)
    {
        sprintf(buffer, "Unable to read output from file '%s'\n", file);
    }
    else
    {
        int len_msg = strlen(msg);
        size_t size_rest = sizeof(buffer) -1 - len_msg;
        memcpy(buffer, msg, len_msg);
        if (size_rest < sizeof(buffer) && (size = read(fd, &buffer[len_msg], size_rest) > 0))
        {
            buffer [size] = 0;
            email_send(replyto, recipients, subject, buffer);
        }
        close(fd);
    }
    return(SUCCESS);
}


void email_send(
    char *replyto,
    char *recipients,
    char *subject,
    char *body)
{
    char command[1280] = {0};
    char host_name[32];
    FILE *po;
    if (subject == 0 || subject[0] == 0)
    {
        subject = "Maskdesigner";
    }
    DBG("libraries/db_libs/shared_client_lib/source/email_send.c");
    DBG("original To: %s", recipients);
    if ( recipients && recipients[0] )
    {
        strcpy(command, recipients);
    }
    if (replyto && replyto[0])
    {
        if (command[0])
        {
            strcat(command, ",");
        }
        strcat(command, replyto);
    }
    if (command[0])
    {
        recipients = (char*)email_check_recipients(command);
    }
    else
    {
         recipients = (char*)email_get_recipients_MaskPrep();
    }
    DBG("handled To: %s", recipients);
    sprintf (command, "/usr/lib/sendmail -f%s %s",
             email_get_common_From(), recipients);
    po = popen (command,"w");
    fprintf(po, "To: %s\n", recipients);

    fprintf(po, "From:  %s\n", email_get_common_From());
    char *user = getenv("USER");
    if (user == NULL)
    {
        user = "unknown";
    }
    fprintf (po, "Subject: [from maskdesigner.%s] %s\n\n", user, subject);

    /* Write out the email body */
    fprintf(po, "%s\n\n", body);
    /* Get the name of the current machine */
    gethostname(host_name, 32);
    fprintf(po, "-- Message generated by %s on %s\n", so.program, host_name);
    if (pclose(po) != 0)
    {
       fprintf(stderr, "ERROR: could not send email of subject:%s\n", subject);
       fprintf(stderr, "        with the body:\n%s\n", body);
    }
    replyto = replyto; /* just avoid warning */
} /* End email_send */
/* Process email messages present in Intercom repository */

#if defined(EMAIL_STANDALONE_TEST) == false  && defined(MDS_SERVER) == false /* used to test */
int fss_email_send(void)
{
    char file_name[FILE_SIZE];
    char email_dir[FILE_SIZE];
    FILE *fp;
    char *file_ptr;
    char line[260];
    char *files[256];
    char from_email[FILE_SIZE];
    int cnt;
    int ret;

    DBG("libraries/db_libs/shared_client_lib/source/email_send.c");
    if ((ret = init_trans_socket(FSS_EMAIL_SEND, NONE, NONE, NONE, 0, 0,
    UNSPECIFIED, NONE_STRING)) < SUCCESS)
    return(ret);
    /* Get directory holding files to send email for */
    strcpy(email_dir, FSS_EMAIL_DIR);
    mkdir(FSS_EMAIL_DIR, 0700);
    cnt = files_get(email_dir, files);
    file_ptr = file_name + strcpy2(file_name, email_dir, "/");
    for (cnt = 0; files[cnt] != NULL; ++cnt)
    {
    /* Build the file name */
    strcpy(file_ptr, files[cnt]);
    if ((fp = fopen(file_name, "r")) == NULL) continue;
    /* Read in the from email address */
    line_get(fp, line);
    line_get(fp, line);
    sscanf(line, "%*s %s", from_email);
    email_file_send(from_email, from_email, file_name, file_name);
    /*
     *    using a single function to send emails
    sprintf(command, "cat %s | /usr/lib/sendmail -f%s -t", file_name, from_email);
    system(command);
    */
    unlink(file_name);
    } /* End for for sending email */
    /* Delete the directory no longer needed */
    dir_dlt(email_dir);
    /* Free list of files no longer needed */
    files_free(files);
    /* Tell server transaction successful */
    put_short(SUCCESS);
    return(get_ret_code());
} /* end fss_email_send */
#endif /* EMAIL_STANDALONE_TEST */
#else
void email_send(
    char *replyto,
    char *recipients,
    char *subject,
    char *body)
{
}

int fss_email_send(void)
{
}
#endif
