#!/bin/sh
# Run this build on angel

M2_SERVER=`pwd`

rm -f mdd


DEBUG=""

if [ "$1" = "-d" ]
then
   DEBUG="-g -DDEBUG -Dexit=FAKE_exit -Dfork=FAKE_fork"
fi


if [ "$1" = "-D" ]
then
   DEBUG="-g -DENABLE_LOGS"
fi

cd ../reg_lib
./mdd8make $1
if [ $? -ne 0 ]
then
     exit 1
fi


pwd
cd ../server_lib
./mdd8make $1
if [ $? -ne 0 ]
then
     exit 1
fi

cd $M2_SERVER


export DEBUG
make MACHINE=SOLARIS local_mdd
exit $?
