/****************************************************************************
*
* Program:	machine_check
*
* Description:	Verifies everything working properly on this machine
*		        to perform specific transactions. To be deployed at
*              /home/db_admin/bin/machine_check and depends on
*              /home/db_admin/bin/machine_config to run
*
***************************************************************************/

#include <sys/file.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <strings.h>
#include <unistd.h>

char program[64];

int line_get(FILE *fp, char *line)
{
    char eof_fnd = 2;
    int cnt;

    cnt = 0;

    while (((line[cnt] = getc(fp)) != '\n') && (line[cnt] != EOF) && (cnt < 1024)) ++cnt;

    /* Set flag if end of file reached */
    if (line[cnt] == EOF) eof_fnd = 1;

    /* Put null at end of line */
    line[cnt] = '\0';

    /* Return the number of characters found */
    /* Return EOF if end of file reached and no characters found */
    if (eof_fnd == 1) return(EOF);
    else return(cnt);
} /* End line_get */

/* Process email messages, build and send it */
void email_send(char *replyto, char *recipients, char *subject, char *body)
{
    char command[512];
    char host_name[32];
    FILE *po;

    if (replyto[0] != 0)
        sprintf (command, "/usr/lib/sendmail  -f%s %s", replyto, recipients);
    else
        sprintf (command, "/usr/lib/sendmail  %s", recipients);

    po = popen (command,"w");
    fprintf (po, "To: %s\n", recipients);

    if (replyto[0] != '\0')
    {
	    fprintf(po, "From:  %s\n", replyto);
	    fprintf(po, "Reply-To:  %s\n", replyto);
    }

    /* Write out the email subject */
    if (subject[0] != '\0')
        fprintf (po, "Subject: %s\n\n", subject);

    /* Write out the email body */
    fprintf(po, "%s\n\n", body);

    /* Get the name of the current machine */
    gethostname(host_name, 32);

    fprintf(po, "-- Message generated by %s on %s\n", program, host_name);

    pclose (po);
    return;
} /* End email_send */


/****** MAIN ******/
int main(int argc, char **argv)
{
    FILE *fi;
    char df_dir[64];
    int current_disk_usage;
    int i;
    char machine_name[64];
    char from_email[64];
    char to_email[64];
    int fnd = 2;
    char buffer[1024];
    char line[260];
    char command[260];
    char subject[260];
    int pid_num;
    int max_num;
    int max_disk_usage;
    FILE *po;

    /* Initialize the program */
    strcpy(program, "machine_check");

    /* First change to directory where command performed */
    if (argc >= 2)
        i = chdir(argv[1]);
    else
    {
	    char *ptr = rindex(argv[0], '/');
	    if (ptr != NULL) ptr[0] = '\0';
	        i = chdir(argv[0]);
    }

    /* Read in data from the configuration file */
    fi = fopen("machine_config", "r");
    if (fi == NULL) exit(666);

    /* Skip past comment lines in file */
    /* These are allowed at the top of the file */
    while (line_get(fi, line) != EOF)
    {
#ifdef DEBUG
        fprintf(stderr, "line '%s'\n", line);
#endif
	    if (line[0] != '#') break;
    }

    /* At this point will have first valid line of text */
    sscanf(line, "%s %s %s %d %d %s", machine_name, from_email, to_email, &max_num, &max_disk_usage, df_dir);

    /* First verify no more than specified number of processes running */
    system("ps -e -opid -oargs >outt");
    po = popen("wc -l outt", "r");
    fscanf(po, "%d", &pid_num);

    if (pid_num > max_num)
    {
	    sprintf(subject, "%d processes on %s", pid_num, machine_name);
	    email_send(from_email, to_email, subject, subject);
    } /* End if for more than 100 processes */

    /* Close the output */
    pclose(po);

    /* Now check disk usage */
    /* Build command */
    sprintf(command, "df -k %s", df_dir);
    po = popen(command, "r");
    line_get(po, line);
#ifdef DEBUG
    fprintf(stderr, "line '%s'\n", line);
#endif
    line_get(po, line);
#ifdef DEBUG
    fprintf(stderr, "line '%s'\n", line);
#endif

#ifdef DTMS
    line_get(po, line);
    /* Now scan in data */
    sscanf(line, "%*s %*s %*s %d", &current_disk_usage);
#else
    sscanf(line, "%*s %*s %*s %*s %d", &current_disk_usage);
#endif

    /* If current usage greater than max usage, send email */
    if (current_disk_usage > max_disk_usage)
    {
	    sprintf(subject, "Disk usage on %s is at %d%%\n", machine_name, current_disk_usage);
	    email_send(from_email, to_email, subject, subject);
    } /* End if for disk usage too high */

    /* Now look for commands specified in input file */
    pclose(po);

    sprintf(buffer, "The following processes are not running:\n\n");

    while (line_get(fi, line) != EOF)
    {
#ifdef DEBUG
        fprintf(stderr, "line '%s'\n", line);
#endif
	    sprintf(command, "grep '%s' outt", line);
	    po = popen(command, "r");
	    if (fscanf(po, "%s", line) == EOF)
	    {
	        fnd = 1;
	        sprintf(buffer, "%s \n", line);
	    } /* End if */
    } /* End while */

    fclose(fi);
    if (fnd == 1)
    {
	    sprintf(subject, "Servers not running on '%s'", machine_name);
	    email_send(from_email, to_email, subject, buffer);
    } /* End if */

    return 0;
}
