#ifndef mask_server_paths_h
#define mask_server_paths_h
/* Defines for mask and template paths */
#define TURNED_OFF_MASKS "db_admin/turned_off_masks"
#define AUDIT_MAIL_LIST "mdsEvents@nxp.com"
#define AUDIT_PATH "audit_log/"
#define RMT_AUDIT_PATH "rmt_audit_log/"
#define CREATE_FILE "create"
#define SLASH "/"
#define NEW_FABS "fab_tech.files/new_fabs"
#define GLOBAL_FAB_FILE "db_admin/global_fab_files"
#define FAB_DIR "/.fab"
#define TECHNOLOGY "technology"
#define SERIAL_DIR "serial_tables"
#define SERIAL_PATH "serial_tables/"
#define CONTRACT_DIR "contract_tables"
#define MASKSET_TABLE "contract_tables/mask_num"
#define MASKSET_ROOT "mask_num"
#define MASKSET_ROOT_LEN 8
#define MASKSET_PREFIX "mask_"
#define MASKSET_PREFIX_LEN 5
#define MASKSET_LOG "contract_tables/mask_log"
#define PC_TABLE "contract_tables/pc_num"
#define PC_ROOT "pc_num"
#define PC_ROOT_LEN 6
#define PC_PREFIX "pc_"
#define PC_PREFIX_LEN 3
#define PC_LOG "contract_tables/pc_log"
#define H_TABLE "contract_tables/h_num"
#define H_ROOT "h_num"
#define H_ROOT_LEN 5
#define H_PREFIX "h_"
#define H_PREFIX_LEN 2
#define H_LOG "contract_tables/h_log"
#define DB_DATA_DIR "db_admin"
#define TMP_DB_DATA_DIR "db_admin/tmp_files"
#define TMP_DB_DATA_PATH "db_admin/tmp_files"
#define DB_DATA_PATH "db_admin"
#define DISK_FILE "db_admin/disk_usage"
#define GLOBAL_AUTH_FILE "db_admin/global.auth"
#define ADMIN_AUTH_FILE "db_admin/admin.auth"
#define PC_APPROVE_FILE "db_admin/pc.approve"
#define PC_BUILD_FILE "db_admin/pc.build"
#define APPROVE_FILE "db_admin/approve.auth"
#define TEMPLATE_AUTH_FILE "db_admin/template.auth"
#define JOC_AUTH_FILE "db_admin/joc.auth"
#define MASKPREPSTATE ".MaskPrepState"
#define RESEND_PATH "resend_data"
#define RESEND_FILE "rmt_log/resend_file"
#define TMP_RESEND_FILE "log/tmp_resend_file"
#define CNB_FILE "db_admin/maskshop.cnb"
#define GLOBAL_DATA "global_data"
#define GLOBAL_DELTA "global_dlta"
#define TMP_GLOBAL_DATA "global_data/new"
#define TMP_GLOBAL_DELTA "global_dlta/new"
#define OFF_GLOBAL_DATA "off_global_data"
#define OFF_GLOBAL_DELTA "off_global_dlta"
#define OFF_JOC_DATA "off_joc_data"
#define OFF_JOC_DELTA "off_joc_dlta"
#define SYSADMIN_AUTH "db_admin/sysadmin.auth"
#define TOKYO_AUTH "db_admin/tokyo.auth"
#define DB_ADMIN_FILE "db_admin/db_admin_file"
#define SYSADMIN_INFO "db_admin/sysadmin.info"
#define APPROVE_INFO "db_admin/approve.info"
#define GLOBAL_MASK_FILE "db_admin/mask.sets"
#define GLOBAL_TECH_FILE "db_admin/fab_tech.tbl"
#define NEW_MASK_FILE "db_admin/mask.sets.new"
#define BACKUP_MASK_FILE ".backup.sets"
#define FAB_DATA "fab_data"
#define TMP_FAB_DATA "fab_data/new"
#define OFF_FAB_DATA "off_fab_data"
#define FAB_DELTA "fab_dlta"
#define TMP_FAB_DELTA "fab_dlta"
#define OFF_FAB_DELTA "off_fab_dlta"
#define CONTROL_GROUP_DIR "control_groups"
#define WLFL_DIR "wafer_design"
#define WLFL_DIR "wafer_design"
#define GLBL_WL_FILE "wafer_design/wafer.lines"
#define WAFER_LIES "wafer.lines"
/* File with names of all closure, orient, option and driver files to send */

/* Defines for global design and wafer line paths  */
#define DESIGN_GROUPS "wafer_design/design.groups"

#define PC_DATA "pc_data"
#define PC_DELTA "pc_dlta"
#define TMP_PC_PATH "pc_dlta/tmp_files"
#define PC_DELTA "pc_dlta"
#define PC_BACKUP "pc_backup"

#define MASK_DATA "mask_data"
#define MASK_DELTA "mask_dlta"

/* Defines for user group paths */
#define USER_DATA "user_data"
#define USER_DELTA "user_dlta"

/* Defines for PC library names */
#define PC_USR ".pc_usr"
#define CRT_SUFFIX ".crt"
#define REMOTE_SERVER_TABLE "db_admin/remote_servers"
#define RMT_SERVER_TABLE "db_admin/rmt_servers"
#define GLOBAL_PARAMS "db_admin/global_params"
#define FILELIST "db_admin/filelist"
#define DB_FILELIST "db_admin/db_filelist"
#define PC_FILE "db_admin/pc_libs"

/* Defines for serial num tables */
#define MOS6SERIAL_PREFIX "mos6"
#define MOS16SERIAL_PREFIX "mos16"
#define MOS17SERIAL_PREFIX "mos17"
#define MOS21SERIAL_PREFIX "mos21"
#define CONTRACT_FILE "db_admin/contract_num"
#define PCNUM_FILE "db_admin/pc_num"
#define SITE_REG_FILE "registry/site_reg."
#endif /* ifdef for mask_server_paths_h */
