#!/bin/sh

# Run this build on angel


DEBUG=""

if [ "$1" = "-d" ]
then
   DEBUG="-g -DDEBUG -Dexit=FAKE_exit -Dfork=FAKE_fork"
fi

if [ "$1" = "-D" ]
then
   DEBUG="-g -DENABLE_LOGS"
fi


export DEBUG
make -f solaris.makefile SSL_OPTION=NO_ENCRYPTION PROGRAM=M2 COMPANY=FREESCALE m2reg_lib.a
exit $?
