# This builds the InterCom API as a shared object

EXTRA_OPTION	=	TRANSAPI 
SSL_OPTION		=	SSL_ENCRYPTION  
MACHINE			=	LINUX64 
SWAP_OPTION		=	BYTESWAP 
SERVER_OPTION	=	SINGLE_CONNECT 
MISC			=	SINGLE_CONNECT 
PROGRAM			=	INTERCOM 
COMPANY			=	EXTERNAL 
#libtrans.so 

mv libtrans.so ../lib
make EXTRA_OPTION=TRANSAPI SSL_OPTION=SSL_ENCRYPTION  MACHINE=LINUX64 SWAP_OPTION=BYTESWAP SERVER_OPTION=SINGLE_CONNECT MISC=SINGLE_CONNECT PROGRAM=INTERCOM COMPANY=EXTERNAL so64icom 
