#ifndef trans_server_arrays_h
#define trans_server_arrays_h
/* Transcend request types */
static char req_array[131][20] =
{
    "Get",
    "Put",
    "Delete",
    "Cron-delete",
    "Info",
    "History",
    "Put tar",
    "Extend",
    "Set user email",
    "Set file email",
    "Cancel user email",
    "Cancel file email",
    "Get-delete",
    "Put-delete",
    "Put-delete",
    "Register_query",
    "Auto register",
    "Manual register",
    "Formal register",
    "Resend registry",
    "Send secure key",
    "Query user",
    "Format Email",
    "Get release",
    "Mod admin",
    "Put dir/links",
    "File size check",
    "Put delete",
    "Release info",
    "Delete old sites",
    "Delete X500",
    "User lock",
    "User unlock",
    "Put",
    "Get",
    "Get delete",
    "Put-delete",
    "X500 authen",
    "Set2ASCII",
    "Set2binary",
    "Remote reg",
    "Icom release",
    "Icom release info",
    "Site check",
     "View keywords",
    "Delete lock",
    "Delete unlock",
    "admin authen", 	/* Verify authorized  sys admin */
     "ping",
    "silent ping",
    "Put report",
    "Usage report",
    "FTP resend",
    "fast user query",
    "User table build",
    "Company table rtv",
    "Query rtv keys",
    "Mettracks",
    "Status",
    "user keys rtv",
    "TransWeb table",
    "TransWeb history",
    "Rtv secure keys",
    "Rtv repository",
    "TransWeb Email",
    "Delete user keys",
    "Delete secure keys",
    "Remote TransWeb Reg",
    "Audit registry",
    "Summary report",
    "Company add",
    "Server set",
    "Rtv FSS logs",
    "FSS email send",
    "Ftp get",
    "Mask delete verify",
    "Support add",
    "Support delete",
    "support view",
     "mask check put",
     "mask list send",
    "mask history",
    "Put duplicate",
    "server register",
    "rmt server register",
    "get zipped",
    "Send mask project",
    "DTMS status check",
    "Get/delete zipped",
    "block put",
    "block get",
    "Put parallel",
    "RandomBlock put",
    "Put random parallel",
    "X500 lookup",
    "File name/mode",
    "Transdirlist rtv",
    "Transdirlist put",
    "parallel get",
	"shmem cleanup",
    "Randomblock get",
    "get random parallel",
    "List extension rtv",
    "Get serial",
    "GUI companies rtv",
    "Get separate",
    "Put separate",
    "registration URL",
    "Lst DTMS test files",
    "transweb log rtv",
    "Separate block put",
    "Separate block get",
    "Encrypt password log",
    "encrypt data",
    "Parallel get delete",
    "Parallel put delete",
    "Approve user",
    "Retrieve approvals",
    "Commandline approve",
    "commandline rtv",
    "Request approval",
    "Extract registry",
    "Build registry",
};

/* Holds names of file types */
static char trans_filetype_array[10][12] =
{
    "ASCII",
    "Binary",
    "Mac binary",
    "Directory",
    "file",
    "Files",
    "Unknown",
    "Directory",
    "File",
    "Files"
};

#endif /* ifdef for trans_server_arrays_h */
